---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Installs the required pip modules
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: finagle Molecule configuration to find Ansible Role
          command: |
            mkdir -p /tmp/molecule/project/default/roles
            ln -nfs /home/circleci/project/ /tmp/molecule/project/default/roles/$CIRCLE_PROJECT_REPONAME
      - run:
          name: run molecule
          command: |
            . venv/bin/activate
            molecule test
workflows:
  version: 2
  build:
    jobs:
      - build
